version: '3'
services:
  server:
    image: btlachac95/discord-trivia-bot-server
    container_name: trivia-server
    environment:
      - DB_USER=${DB_USER}  
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_SERVER=db_postgres
      - AUDIO_FILE_DIRECTORY=${AUDIO_FILE_DIRECTORY}
      - TRIVIA_HOST_TOKEN=${TRIVIA_HOST_TOKEN}
      - TRIVIA_CHANNEL_ID=${TRIVIA_CHANNEL_ID}
      - COMMAND_CHANNEL_ID=${COMMAND_CHANNEL_ID}
      - GUILD_ID=${GUILD_ID}
      - AUDIO_CHANNEL_ID=${AUDIO_CHANNEL_ID}
    ports: 
      - 8080:8080 
    restart: on-failure
    volumes:
      - api:${AUDIO_FILE_DIRECTORY}
    depends_on:
      - db
    networks:
      - fullstack

  db:
    image: postgres:latest
    container_name: db_postgres
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - fullstack
      
  ui:
    image: btlachac95/discord-trivia-bot-ui
    container_name: trivia-ui
    environment:
      - API_URL=http://trivia-server:8080
    ports: 
      - 5000:5000 
    restart: on-failure
    depends_on:
      - server
    networks:
      - fullstack

volumes:
  api:
  database_postgres:   

# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge
