
version: '3'
services:
  server:
    container_name: trivia-server
    environment:
      - DB_USER=${DB_USER}  
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_SERVER=${DB_SERVER} 
      - AUDIO_FILE_DIRECTORY=${AUDIO_FILE_DIRECTORY}
    build: ./trivia-server
    ports: 
      - 8080:8080 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - db
    networks:
      - fullstack
      
  db:
    image: postgres:latest
    container_name: db_postgres
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_SERVER} 
    ports:
      - '5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - fullstack
      
  ui:
    container_name: trivia-ui
    environment:
      - API_URL=${API_URL}  
    build: ./trivia-ui
    volumes:
    - ./trivia-ui:/trivia-ui/
    ports: 
      - 5000:5000 
    restart: on-failure

  bots:
    container_name: trivia-bots
    environment:
      - API_URL=${API_URL}
    build: ./trivia-bots
    restart: on-failure

volumes:
  api:
  database_postgres:   

# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge
